In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_excel(r"C:\AutoMPGmodels.xlsx")

In [26]:
dataset.head(25)

,GallonsPer100Miles,GallonsPer100MilesTo1981,MPG,Cylinders,Displacement100ci,Horsepower100,Weight1000lb,Seconds0to60,Year,Year70To81,Origin,Origin.Eq.1,Origin.Eq.2,Origin.Eq.3,Name
0,5.555556,5.555556,18.0,8.0,3.07,1.30,3.504,12.0,70.0,1.0,1.0,1.0,0.0,0,chevrolet chevelle malibu
1,6.666667,6.666667,15.0,8.0,3.50,1.65,3.693,11.5,70.0,1.0,1.0,1.0,0.0,0,buick skylark 320
2,5.555556,5.555556,18.0,8.0,3.18,1.50,3.436,11.0,70.0,1.0,1.0,1.0,0.0,0,plymouth satellite
3,6.250000,6.250000,16.0,8.0,3.04,1.50,3.433,12.0,70.0,1.0,1.0,1.0,0.0,0,amc rebel sst
4,5.882353,5.882353,17.0,8.0,3.02,1.40,3.449,10.5,70.0,1.0,1.0,1.0,0.0,0,ford torino
5,6.666667,6.666667,15.0,8.0,4.29,1.98,4.341,NaN,70.0,1.0,1.0,1.0,0.0,0,ford galaxie 500
6,7.142857,7.142857,14.0,8.0,4.54,2.20,4.354,9.0,70.0,1.0,1.0,1.0,0.0,0,chevrolet impala
7,7.142857,7.142857,14.0,8.0,4.40,2.15,4.312,8.5,70.0,1.0,1.0,1.0,0.0,0,plymouth fury iii
8,7.142857,7.142857,14.0,8.0,4.55,2.25,4.425,10.0,70.0,1.0,1.0,1.0,0.0,0,pontiac catalina
9,6.666667,6.666667,15.0,8.0,3.90,1.90,3.850,8.5,70.0,1.0,1.0,1.0,0.0,0,amc ambassador dpl
10,6.666667,NaN,15.0,8.0,NaN,1.70,NaN,10.0,70.0,1.0,1.0,1.0,0.0,0,dodge challenger se
11,7.142857,7.142857,14.0,8.0,3.40,1.60,3.609,8.0,70.0,1.0,1.0,1.0,0.0,0,plymouth 'cuda 340
12,6.666667,6.666667,15.0,8.0,4.00,1.50,3.761,9.5,70.0,1.0,1.0,1.0,0.0,0,chevrolet monte carlo
13,7.142857,7.142857,14.0,8.0,4.55,2.25,3.086,10.0,70.0,1.0,1.0,1.0,0.0,0,buick estate wagon (sw)
14,4.166667,4.166667,24.0,4.0,1.13,0.95,2.372,15.0,70.0,1.0,3.0,0.0,0.0,1,toyota corona mark ii
15,4.545455,4.545455,22.0,6.0,1.98,0.95,2.833,15.5,70.0,1.0,1.0,1.0,0.0,0,plymouth duster
16,5.555556,5.555556,18.0,6.0,1.99,0.97,2.774,15.5,70.0,1.0,1.0,1.0,0.0,0,amc hornet
17,4.761905,4.761905,21.0,6.0,2.00,0.85,2.587,16.0,70.0,1.0,1.0,1.0,0.0,0,ford maverick
18,3.703704,3.703704,27.0,4.0,0.97,0.88,2.130,14.5,70.0,1.0,3.0,0.0,0.0,1,datsun pl510
19,3.846154,3.846154,26.0,4.0,0.97,0.46,1.835,20.5,70.0,1.0,2.0,0.0,1.0,0,volkswagen 1131 deluxe sedan
20,4.000000,4.000000,25.0,4.0,1.10,0.87,2.672,17.5,70.0,1.0,2.0,0.0,1.0,0,peugeot 504
21,4.166667,4.166667,24.0,4.0,1.07,0.90,2.430,14.5,70.0,1.0,2.0,0.0,1.0,0,audi 100 ls
22,4.000000,4.000000,25.0,4.0,1.04,0.95,2.375,17.5,70.0,1.0,2.0,0.0,1.0,0,saab 99e
23,3.846154,3.846154,26.0,4.0,1.21,1.13,2.234,12.5,70.0,1.0,2.0,0.0,1.0,0,bmw 2002
24,4.761905,4.761905,21.0,6.0,1.99,0.90,2.648,15.0,70.0,1.0,1.0,1.0,0.0,0,amc gremlin

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   GallonsPer100Miles        391 non-null    float64
 1   GallonsPer100MilesTo1981  355 non-null    float64
 2   MPG                       389 non-null    float64
 3   Cylinders                 391 non-null    float64
 4   Displacement100ci         384 non-null    float64
 5   Horsepower100             387 non-null    float64
 6   Weight1000lb              377 non-null    float64
 7   Seconds0to60              385 non-null    float64
 8   Year                      390 non-null    float64
 9   Year70To81                390 non-null    float64
 10  Origin                    389 non-null    float64
 11  Origin.Eq.1               390 non-null    float64
 12  Origin.Eq.2               390 non-null    float64
 13  Origin.Eq.3               392 non-null    int64
 14  Name                      374 non-null    object
dtypes: float64(13), int64(1), object(1)
memory usage: 46.1+ KB

In [8]:
dataset.select_dtypes(include = "float64" ).columns

Index(['GallonsPer100Miles', 'GallonsPer100MilesTo1981', 'MPG', 'Cylinders',
       'Displacement100ci', 'Horsepower100', 'Weight1000lb', 'Seconds0to60',
       'Year', 'Year70To81', 'Origin', 'Origin.Eq.1', 'Origin.Eq.2'],
      dtype='object')

In [19]:
from sklearn.impute import SimpleImputer

In [31]:
si = SimpleImputer(strategy = "mean")
arr = si.fit_transform(dataset[['GallonsPer100Miles', 'GallonsPer100MilesTo1981', 'MPG', 'Cylinders',
       'Displacement100ci', 'Horsepower100', 'Weight1000lb', 'Seconds0to60',
       'Year', 'Year70To81', 'Origin', 'Origin.Eq.1', 'Origin.Eq.2']])

In [32]:
new_data = pd.DataFrame(arr,columns = dataset.select_dtypes(include = "float64").columns)

In [30]:
new_data.head(25)

,GallonsPer100Miles,GallonsPer100MilesTo1981,MPG,Cylinders,Displacement100ci,Horsepower100,Weight1000lb,Seconds0to60,Year,Year70To81,Origin,Origin.Eq.1,Origin.Eq.2
0,5.555556,5.555556,18.0,8.0,3.07000,1.30,3.504000,12.000000,70.0,1.0,1.0,1.0,0.0
1,6.666667,6.666667,15.0,8.0,3.50000,1.65,3.693000,11.500000,70.0,1.0,1.0,1.0,0.0
2,5.555556,5.555556,18.0,8.0,3.18000,1.50,3.436000,11.000000,70.0,1.0,1.0,1.0,0.0
3,6.250000,6.250000,16.0,8.0,3.04000,1.50,3.433000,12.000000,70.0,1.0,1.0,1.0,0.0
4,5.882353,5.882353,17.0,8.0,3.02000,1.40,3.449000,10.500000,70.0,1.0,1.0,1.0,0.0
5,6.666667,6.666667,15.0,8.0,4.29000,1.98,4.341000,15.562078,70.0,1.0,1.0,1.0,0.0
6,7.142857,7.142857,14.0,8.0,4.54000,2.20,4.354000,9.000000,70.0,1.0,1.0,1.0,0.0
7,7.142857,7.142857,14.0,8.0,4.40000,2.15,4.312000,8.500000,70.0,1.0,1.0,1.0,0.0
8,7.142857,7.142857,14.0,8.0,4.55000,2.25,4.425000,10.000000,70.0,1.0,1.0,1.0,0.0
9,6.666667,6.666667,15.0,8.0,3.90000,1.90,3.850000,8.500000,70.0,1.0,1.0,1.0,0.0
10,6.666667,4.884115,15.0,8.0,1.92793,1.70,2.959257,10.000000,70.0,1.0,1.0,1.0,0.0
11,7.142857,7.142857,14.0,8.0,3.40000,1.60,3.609000,8.000000,70.0,1.0,1.0,1.0,0.0
12,6.666667,6.666667,15.0,8.0,4.00000,1.50,3.761000,9.500000,70.0,1.0,1.0,1.0,0.0
13,7.142857,7.142857,14.0,8.0,4.55000,2.25,3.086000,10.000000,70.0,1.0,1.0,1.0,0.0
14,4.166667,4.166667,24.0,4.0,1.13000,0.95,2.372000,15.000000,70.0,1.0,3.0,0.0,0.0
15,4.545455,4.545455,22.0,6.0,1.98000,0.95,2.833000,15.500000,70.0,1.0,1.0,1.0,0.0
16,5.555556,5.555556,18.0,6.0,1.99000,0.97,2.774000,15.500000,70.0,1.0,1.0,1.0,0.0
17,4.761905,4.761905,21.0,6.0,2.00000,0.85,2.587000,16.000000,70.0,1.0,1.0,1.0,0.0
18,3.703704,3.703704,27.0,4.0,0.97000,0.88,2.130000,14.500000,70.0,1.0,3.0,0.0,0.0
19,3.846154,3.846154,26.0,4.0,0.97000,0.46,1.835000,20.500000,70.0,1.0,2.0,0.0,1.0
20,4.000000,4.000000,25.0,4.0,1.10000,0.87,2.672000,17.500000,70.0,1.0,2.0,0.0,1.0
21,4.166667,4.166667,24.0,4.0,1.07000,0.90,2.430000,14.500000,70.0,1.0,2.0,0.0,1.0
22,4.000000,4.000000,25.0,4.0,1.04000,0.95,2.375000,17.500000,70.0,1.0,2.0,0.0,1.0
23,3.846154,3.846154,26.0,4.0,1.21000,1.13,2.234000,12.500000,70.0,1.0,2.0,0.0,1.0
24,4.761905,4.761905,21.0,6.0,1.99000,0.90,2.648000,15.000000,70.0,1.0,1.0,1.0,0.0